---
- hosts: all
  vars_files:
      - secrets.yml
  remote_user: root
  tasks:
    - name: Install dependencies
      apt: 
        update_cache: yes
        force_apt_get: yes
        pkg:
        - apt-transport-https
        - curl
        - ca-certificates
        - gnupg

    - name: Add docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Setup wireguard easy
      docker_container:
        name: wg-easy
        image: weejewel/wg-easy
        state: started
        restart: yes
        restart_policy: unless-stopped
        env:
            WG_HOST: "{{ wireguard_easy_ip }}"
            # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
            PASSWORD: "{{ wireguard_easy_password }}"
        volumes:
        - ~/.wg-easy:/etc/wireguard
        ports:
        - "51820:51820/udp"
        - "51821:51821/tcp"
        capabilities:
        - net_admin
        - sys_module
        sysctls: {
            "net.ipv4.conf.all.src_valid_mark": "1",
            "net.ipv4.ip_forward": "1",
        }
        

# docker run -d \
#   --name=wg-easy \
#   -e WG_HOST=🚨YOUR_SERVER_IP \
#   -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
#   -v ~/.wg-easy:/etc/wireguard \
#   -p 51820:51820/udp \
#   -p 51821:51821/tcp \
#   --cap-add=NET_ADMIN \
#   --cap-add=SYS_MODULE \
#   --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
#   --sysctl="net.ipv4.ip_forward=1" \
#   --restart unless-stopped \
#   weejewel/wg-easy


# '{{ ansible_default_ipv4.address }}'



